---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "ITRS-Group/team-b"
    ignore:
      - dependency-name: boto3
        # For boto3 we ignore all 1.17.x updates
        versions: 1.17.x
