pre:
  steps: |
    set -ex
    cd src
    rm -rf venv dist wheels test-wheels

    python3.12 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install poetry wheel
    poetry self add poetry-plugin-export

    # Install all dependencies to run tests
    poetry install --no-interaction --no-root
    poetry run mypy check_aws
    poetry run autoflake --recursive check_aws tests
    poetry run black check_aws tests --check

    # We build all the wheels now while we can access PyPI and github repos
    poetry build -f wheel  # writes to dist/
    poetry export --with test -f requirements.txt --without-hashes -o requirements.txt
    pip wheel -r requirements.txt -w dist/
    rm requirements.txt

    # Also include the current pip version so it can be used in the installation
    pip wheel pip -w dist/

post:
  steps: |
    set -ex
    # Smoke test
    /opt/plugins/check_aws.py --help

    if [ ${RHEL_VERSION:-0} -ge 8 ]; then
      # Run unit tests using the installed check_aws package and dependencies
      # from rpm repos.

      # Prevent Python from importing check_aws from CWD instead of the installed package:
      mv check_aws{,.src}

      # Activate venv
      source /opt/monitor/op5/check_aws/venv/bin/activate
      # Run tests
      python -m pytest -v
      if [ -n "${CODECOV_TOKEN}" ]; then
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
      fi
    fi
